### ISSUE TITLE
Add support for the new controller that comes with the PS4 Slim

### ISSUE THREAD

**Issue by sylveon** [nefarius/FireShock#11]
Right now it won't install automatically and attempting to force install the driver results in a failure with error STATUS_DEVICE_POWER_FAILURE

**Comment by nefarius** [comment]
If I'd own one I'd take a look at it 😸

**Comment by mirh** [comment]
https://patchwork.kernel.org/patch/9367441/ ?

**Comment by nefarius** [comment]
@mirh thanks!

**Comment by nefarius** [comment]
I've added it, could someone verify and give feedback please.

**Comment by charlesmilette** [comment]
Will do once I get USB passthrough working on my VM

**Comment by charlesmilette** [comment]
I never got passthrough working and I don’t want to install a self-compiled driver on my machine because of all the secure boot stuff. I guess I’ll wait for a signed driver release

**Comment by nefarius** [comment]
@charlesmilette I'll ship a new signed build then 😉

**Comment by charlesmilette** [comment]
Any news on the signed build? ViGEm got one, but not FireShock (which is
the thing I need to test)

**Comment by JoshWobbles** [comment]
Seems like he may be holding off because of this: https://github.com/nefarius/FireShock/issues/4#issuecomment-309850075

**Comment by mirh** [comment]
https://downloads.vigem.org/fireshock/stable/2.0.0.0/windows/

**Comment by sylveon** [comment]
Yeah after a few discussions on Discord I've been using that with Shibari for a while.
