### ISSUE TITLE
FireShock doesn't completely uninstall itself

### ISSUE THREAD

**Issue by Alia5** [nefarius/FireShock#12]
After installing / uninstalling Fireshock, DS3 Controllers still get shown as "FireShock 3" Device.
This even holds true when installing the "official driver" via the PSNow software.

The controller works as expected though (or doesn't work without any driver, ofc.)

My best guess would be a leftover registry value, but I didn't check any further...

![2017-02-16_1705](https://cloud.githubusercontent.com/assets/3527662/23029501/0d1bfc60-f46b-11e6-8397-e1e056a5d9de.png)

**Comment by charlesmilette** [comment]
The driver didn’t got removed, you can do so with the driver manager by right-clicking on the device.

De : Peter Repukat
Envoyé le :16 février 2017 11:12
À : nefarius/FireShock
Cc : Subscribed
Objet :[nefarius/FireShock] FireShock doesn't completely uninstall itself(#12)

After installing / uninstalling Fireshock, DS3 Controllers still get shown as "FireShock 3" Device.
This even holds true when installing the "official driver" via the PSNow software.
The controller works as expected though (or doesn't work without any driver, ofc.)
My best guess would be a leftover registry value, but I didn't check any further...

**Comment by Alia5** [comment]
I tried to do that, didn't change anything.

Upon closer inspection, though. The issue is not with FireShock, but rather ViGEm's HidGuardian-Driver...
![2017-02-16_1950](https://cloud.githubusercontent.com/assets/3527662/23035952/53f5b084-f481-11e6-935e-fa40ce3bd832.png)

I guess this can be "moved" now...
