### ISSUE TITLE
Rumble with DualShock3?

### ISSUE THREAD

**Issue by 252rer** [nefarius/FireShock#17]
I can't seem to get rumble to work for my ds3 controller. Is this something I need ViGEm
 for or is it just not implemented in Fireshock yet?

**Comment by nefarius** [comment]
It is implemented but it ofc. depends on the Game if it utilizes ForceFeedback. You might have more success in conjunction with ViGEm although I have to admit that from my memory I can't a 100% approve that rumble is implemented there 😉

**Comment by charlesmilette** [comment]
Last I tried with ViGEm rumble wasn’t working

**Comment by nefarius** [comment]
@charlesmilette welp, another entry for the roadmap 🤣

**Comment by nefarius** [comment]
Version 1.x is obsolete and so are related issues. v2 will be published soon™.
