### ISSUE TITLE
Not working with 3rd party PS3 controller

### ISSUE THREAD

**Issue by ahmedawy** [nefarius/FireShock#18]
The driver make "Battlefield 4 gamepad: PS3" stop

Device USB\VID_0E6F&PID_0132\6&310cd63b&0&2 was started.

Driver Name: input.inf
Class GUID: {745A17A0-74D3-11D0-B6FE-00A0C90F57DA}
Service: HidUsb
Lower Filters: 
Upper Filters:

**Comment by nefarius** [comment]
Well, this driver is for original Sony DualShock controllers...

**Comment by mirh** [comment]
Is it really any harder than just adding the DID, like with shield driver?

**Comment by JoshWobbles** [comment]
If the ID missing from the INF were the only thing hold this back you would probibly be able to just force the driver on the device
