### ISSUE TITLE
[Solved, sorry] L2 and R2 Analog backwords in Dolphin

### ISSUE THREAD

**Issue by XSuperMarioX** [nefarius/FireShock#2]
In Dolphin, when I set L2 and R2 as L-Analog and R-Analog by holding them down to bypass the L2 and R2 button inputs, they appear to work backwards.  Pressed when not pressed and will unpress when pressing.  When testing the official PS3 controller drivers that you PMd me on twitter, this did not happen so I believe it's an issue with the FireShock drivers.
----
I figured it out, if this comes up again, make sure the person starts pushing in as they setup their buttons.  Each one uses a + to - or - to +.  Sorry about that.

**Comment by nefarius** [comment]
😉
