### ISSUE TITLE
Ram leak.

### ISSUE THREAD

**Issue by Rikimaruaxu** [nefarius/FireShock#20]
With the latest Fireshock installed, My Ram usage goes up indefinitely, With the ps3 controller plugged in it eventually gets to 12-14 gigs of ram used on my 16 gig system, and after unplugging the controller it drops to 476MB, There is a leak somewhere, and It might have something to do with the rumble not working/being super delayed.

**Comment by mirh** [comment]
Could you try some of [this](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/using-poolmon-to-find-a-kernel-mode-memory-leak) stuff perhaps?

**Comment by Rikimaruaxu** [comment]
Will in a few days. had uninstalled it and returned to using SCP toolkit, gonna finish the ps2 game I'm playing, And then i can use that to see where the leak is coming from in Fireshock.

**Comment by nefarius** [comment]
Fixed by rewrite.
