### ISSUE TITLE
[FUN] Signing for Vista and below

### ISSUE THREAD

**Issue by mirh** [nefarius/FireShock#21]
So, it's like [some](https://github.com/nefarius/FireShock/issues/4#issuecomment-309863397) months I had this playful wonder in mind, but I didn't want to disrupt your summer/holidays/mood/sensibility, especially after your complicated [quest for happiness](https://github.com/nefarius/FireShock/tree/master/Signing) had just ended. 

You up for some quality time with [dual signing](https://successfulsoftware.net/2016/01/22/software-sha1-sha2-digital-certificates/)?

**Comment by nefarius** [comment]
I'm using UMDF 2 now which isn't available below Windows 8.1, sorry.
