### ISSUE TITLE
Lilypad source?

### ISSUE THREAD

**Issue by fr500** [nefarius/FireShock#25]
Hey

Where is the source for the modified lilypad driver?
I'm trying to hookup analog buttons to RetroArch's dinput driver and I need an example

Thanks!

**Comment by nefarius** [comment]
It's in my forked repo of PCSX2 but it's becoming obsolete - again - with FireShock v2 coming along.

**Comment by fr500** [comment]
Ah, well I just want to see how to read pressure sensitive buttons

**Comment by nefarius** [comment]
Found it, [here you go](https://github.com/nefarius/pcsx2/tree/8e0a3e1d285aa59497f688534379343f814dbdc8/plugins/LilyPad).
