### ISSUE TITLE
Seems to work flawlessly but game become laggy after few minutes 

### ISSUE THREAD

**Issue by Sephiroth98** [nefarius/FireShock#3]
Hi, thanks for the driver, just tried with Street Fighter IV Ultra on steam, all fine but after few minutes the game a bit unresponsive, stutter background music, etc. If I unplug and plug the usb cable again everything seems back to normal, but not for long, few more minutes got the same issue again.

**Comment by nefarius** [comment]
Are you using it in conjunction with ViGEm? What are your system specs? CPU load during gameplay?

**Comment by sun7** [comment]
I met the same issue.
I'm using FireShock with ViGEm.after a while,game gets lag with out voice and my game controller doesn't work.so,I quit the game and found my PC still working. I opened the TaskManger.
![qq 20161019190533](https://cloud.githubusercontent.com/assets/17898638/19516700/c45716e8-962f-11e6-9efb-39fe9960d9cf.png)
            <<<up here is process Windows Audio Device Graphics Isolated>>>
![qq 20161019190445](https://cloud.githubusercontent.com/assets/17898638/19516773/3452891e-9630-11e6-8de9-b07f54f328c7.png)
            <<<it's my Audio Device currerntly that time >>>
I'm using a Faked (so called= =) dual shock 3 controller without a sound output device.

Hope this will get help 👍

**Comment by c0dycode** [comment]
That's something he's already investigating. I told him about the sound device on twitter.

I'm using a real Sixaxis DualShock3. This happens for me, when I press UP on the DPAD. You could try if that's also the case for you.

**Comment by nefarius** [comment]
One issue, one topic please. The sound device is caused by ViGEm not by FS.

**Comment by nefarius** [comment]
@Sephiroth98 [This should fix it](https://github.com/nefarius/FireShock/files/574048/FireShock_Setup_1.1.0.exe.zip)

**Comment by nefarius** [comment]
Any updates on your end? Could you test the linked release?
