### ISSUE TITLE
Only one controller connected, but stuck as controller 2?

### ISSUE THREAD

**Issue by jacobmix** [nefarius/FireShock#8]
I got only one controller connected, but it's stuck as controller 2.
A way to change controller number or something would be nice.

Using Windows 10 Home 64-bit.
And here's my devices if that helps:
![devices](https://cloud.githubusercontent.com/assets/5995327/20091044/d5032a70-a590-11e6-8225-c3706bf0e6cd.png)

**Comment by JoshWobbles** [comment]
XInput itself determines "player" numbers, not applications. Unplug all your controllers then go into your devices manager and try removing all instances of HID Game controller, Wireless controller, and 360 controllers in there. Then plug in only your DS3 and with all the phantom or ghost controllers gone it should drop to player one.

**Comment by nefarius** [comment]
Due to the XUSB architecture it's not possible to force a controller slot number since the system decides this depending on controller connection order. So you should be fine with @JoshWobbles suggestion.

**Comment by nefarius** [comment]
Well, this idled long enough...
