### ISSUE TITLE
Navigation Controller 

### ISSUE THREAD

**Issue by patsusername81** [nefarius/FireShock#9]
Did anyone ever send you a Nav. Controller or did you ever acquire one?? If not they have them on Ebay and I would be happy to purchase one and have it sent to you. I am new to git hub and am very sorry if this was the improper way to ask about this. I use my Nav. Controller for almost every game that I play so I wanted to make sure that if at all possible your new native driver supported it.

**Comment by JoshWobbles** [comment]
Its already included

**Comment by nefarius** [comment]
I still don't own one 😉
